version: '2'

services:

  subversion:
    image: marvambass/subversion
    ports:
      - 4000:443
    volumes:
      - ./svn/svn:/var/local/svn:rw
      - ./svn/backup:/var/svn-backup:rw
      - ./svn/conf:/etc/apache2/dav_svn/:rw
    restart: always

  openldap:
    image: dinkel/openldap
    ports:
      - 389:389
    environment:
      SLAPD_PASSWORD: secret
      SLAPD_DOMAIN: ldap.example.org
    volumes:
      - ./ldap/config:/etc/ldap:rw
      - ./ldap/data:/var/lib/ldap:rw
    restart: always

  jenkins:
    build: jenkins_build
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home:rw

  redmine:
    image: redmine
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db:postgres
    restart: always

  db:
    image: postgres
    volumes:
      - ./pgdata/:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
    restart: always
